/* eslint max-lines: ["error", 280], max-lines-per-function: ["error", 220] */

const fs = require('fs');
const assert = require('assert');
const yaml = require('js-yaml');

const sgfconv = require('../src/sgfconv');
const GameTree = require('../src/gametree');

const yamlpath = require.resolve('../src/analyze-sgf.yml');

const opts = yaml.load(fs.readFileSync(yamlpath));
opts.sgf.boardYSize = opts.analysis.boardYSize;
const sgfopts = opts.sgf;

// Removes line feeds and comments.
function strip(sgf) {
  return sgf
    .replace(/\r\n/g, '')
    .replace(/\n/g, '')
    .replace(/\\\]/g, '@$$yy$$@')
    .replace(/\bC\[[^\]]*\]/g, '')
    .replace(/@$$yy$$@/g, '\\]');
}

// Compares expected SGF except comments to the SGF generated by GameTree and
// Analysis JSON.
function compareButComments(json, expected) {
  const data = fs.readFileSync(json).toString();
  const index = data.indexOf('\n');
  const sgf = sgfconv.correctSGFDialects(data.substring(0, index));
  const responses = data.substring(index + 1);

  const gametree = new GameTree(sgf, responses, sgfopts);
  const rsgf = strip(gametree.getSGF());
  const esgf = strip(fs.readFileSync(expected).toString());

  assert.equal(esgf, rsgf);
}

// Compares expected SGF to the SGF generated by Analysis JSON.
function compare(json, expected) {
  const data = fs.readFileSync(json).toString();
  const index = data.indexOf('\n');
  const sgf = sgfconv.correctSGFDialects(data.substring(0, index));
  const responses = data.substring(index + 1);

  const gametree = new GameTree(sgf, responses, sgfopts);
  const rsgf = gametree.getSGF();

  assert.equal(fs.readFileSync(expected).toString(), rsgf);
}

describe('GameTree', () => {
  it('should remove the comment of root node, and add move comment.', () => {
    const compareButLines = (x, y) =>
      assert.equal(x.replace(/\n/g, ''), y.replace(/\n/g, ''));
    const gametree = new GameTree('(PL[]C[12\n34];B[aa];W[bb])', '', opts);
    compareButLines(
      gametree.getSGF(),
      '(;PL[]CA[UTF-8];B[aa]C[Move 1];W[bb]C[Move 2])',
    );
  });

  it('should format variations with board size from SGF.', () => {
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [{ pv: ['A1'], winrate: 0.5, scoreLead: 0, visits: 10 }],
    })}\n`;
    const gametree = new GameTree('(;SZ[9];B[bb])', responses, sgfopts);

    assert(gametree.getSGF().indexOf('1. A9') !== -1);
  });

  it('should expose raw KataGo choice rank before filtering.', () => {
    const gopts = { ...sgfopts, maxVariationsForEachMove: 1 };
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [
        { pv: ['A1', 'B2'], winrate: 0.51, scoreLead: 2, visits: 10 },
        { pv: ['C3', 'D4'], winrate: 0.52, scoreLead: 1, visits: 9 },
      ],
    })}\n${JSON.stringify({
      turnNumber: 1,
      rootInfo: { winrate: 0.49, scoreLead: -1, visits: 10 },
      moveInfos: [],
    })}\n`;
    const gametree = new GameTree('(;B[cc])', responses, gopts);

    assert.equal(gametree.nodes[0].rawChoiceRank, 1);
    assert.equal(gametree.nodes[0].choice, -1);
    assert.deepEqual(gametree.nodes[0].classification, {
      category: 'good',
      scoreLoss: 1,
      winrateLoss: 1,
      scoreCategory: 'good',
      winrateCategory: 'excellent',
      severity: 3,
      isTopChoice: false,
    });
    assert.equal(gametree.getSGF().indexOf('* KataGo choice'), -1);
  });

  it('should classify KataGo top choice as zero loss from moveInfos.', () => {
    const gopts = { ...sgfopts, commentStyle: 'compact', language: 'en' };
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [{ pv: ['A1'], winrate: 0.51, scoreLead: 1 }],
    })}\n${JSON.stringify({
      turnNumber: 1,
      rootInfo: { winrate: 0.51, scoreLead: 0.36, visits: 10 },
      moveInfos: [],
    })}\n`;
    const gametree = new GameTree('(;B[aa])', responses, gopts);

    assert.deepEqual(gametree.nodes[0].classification, {
      category: 'best',
      scoreLoss: 0,
      winrateLoss: 0,
      scoreCategory: 'best',
      winrateCategory: 'best',
      severity: 0,
      isTopChoice: true,
    });
    assert(gametree.getSGF().indexOf('Estimated loss: 0.0 points') !== -1);
    assert(gametree.getSGF().indexOf('Victory impact: -0.0%') !== -1);
  });

  it('should classify white move loss from moveInfos perspective.', () => {
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [],
    })}\n${JSON.stringify({
      turnNumber: 1,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [
        { pv: ['A1'], winrate: 0.49, scoreLead: -2 },
        { pv: ['B2'], winrate: 0.5, scoreLead: -0.8 },
      ],
    })}\n${JSON.stringify({
      turnNumber: 2,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [],
    })}\n`;
    const gametree = new GameTree('(;B[aa];W[bb])', responses, sgfopts);

    assert.equal(gametree.nodes[1].rawChoiceRank, 1);
    assert.deepEqual(gametree.nodes[1].classification, {
      category: 'good',
      scoreLoss: 1.2,
      winrateLoss: 0,
      scoreCategory: 'good',
      winrateCategory: 'excellent',
      severity: 3,
      isTopChoice: false,
    });
  });

  it('should expose -1 when played move is absent from raw choices.', () => {
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [
        { pv: ['A1', 'B2'], winrate: 0.51, scoreLead: 1, visits: 10 },
        { pv: ['C3', 'D4'], winrate: 0.52, scoreLead: 2, visits: 9 },
      ],
    })}\n`;
    const gametree = new GameTree('(;B[dd])', responses, sgfopts);

    assert.equal(gametree.nodes[0].rawChoiceRank, -1);
  });

  it('should use propagated custom classification thresholds.', () => {
    const gopts = {
      ...sgfopts,
      classification: { goodMaxScoreLoss: 2.0 },
    };
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [
        { pv: ['A1', 'B2'], winrate: 0.51, scoreLead: 2 },
        { pv: ['B2', 'C3'], winrate: 0.5, scoreLead: 0.5 },
      ],
    })}\n${JSON.stringify({
      turnNumber: 1,
      rootInfo: { winrate: 0.49, scoreLead: -1.5, visits: 10 },
      moveInfos: [],
    })}\n`;
    const gametree = new GameTree('(;B[bb])', responses, gopts);

    assert.equal(gametree.nodes[0].classification.category, 'good');
  });

  it('should render compact comments in generated SGF.', () => {
    const gopts = { ...sgfopts, commentStyle: 'compact', language: 'en' };
    const responses = `${JSON.stringify({
      turnNumber: 0,
      rootInfo: { winrate: 0.5, scoreLead: 0, visits: 10 },
      moveInfos: [{ pv: ['A1', 'B2'], winrate: 0.51, scoreLead: 1 }],
    })}\n${JSON.stringify({
      turnNumber: 1,
      rootInfo: { winrate: 0.51, scoreLead: 1.25, visits: 10 },
      moveInfos: [],
    })}\n`;
    const gametree = new GameTree('(;B[aa])', responses, gopts);
    const sgf = gametree.getSGF();

    assert(sgf.indexOf('Move 1 - Black - Best') !== -1);
    assert(sgf.indexOf('Estimated loss: 0.0 points') !== -1);
    assert(sgf.indexOf('Victory impact: -0.0%') !== -1);
    assert(sgf.indexOf('Best choice: A19') !== -1);
  });

  it('should be expected values for "t-sabaki-1-default.sgf".', () => {
    sgfopts.maxVariationsForEachMove = 10;
    sgfopts.maxWinrateDropForGoodMove = 2;
    sgfopts.minWinrateDropForBadMove = 5;
    sgfopts.minWinrateDropForBadHotSpot = 20;
    sgfopts.minWinrateDropForVariations = 5;
    sgfopts.showVariationsAfterLastMove = false;
    sgfopts.analyzeTurns = undefined;
    compareButComments(
      'test/examples/t-sabaki-1.json',
      'test/examples/t-sabaki-1-default.sgf',
    );
  });

  it('should add passing move for "t-sabaki-1-lastmove.sgf".', () => {
    sgfopts.showVariationsAfterLastMove = true;
    sgfopts.analyzeTurns = undefined;
    compareButComments(
      'test/examples/t-sabaki-1.json',
      'test/examples/t-sabaki-1-lastmove.sgf',
    );
  });

  it('should add passing move and all the variations.', () => {
    sgfopts.showVariationsAfterLastMove = true;
    sgfopts.analyzeTurns = [0, 1, 2, 3, 4, 5];
    compareButComments(
      'test/examples/t-sabaki-1.json',
      'test/examples/t-sabaki-1-turns-lastmove.sgf',
    );
  });

  it('should add all the variations.', () => {
    sgfopts.showVariationsAfterLastMove = false;
    compareButComments(
      'test/examples/t-sabaki-1.json',
      'test/examples/t-sabaki-1-turns.sgf',
    );
  });

  it('should be same for each comment of "t-sabaki-2.sgf".', () => {
    sgfopts.minWinrateDropForVariations = -100;
    sgfopts.showBadVariations = true;
    sgfopts.maxVariationsForEachMove = 20;
    sgfopts.showVariationsAfterLastMove = true;
    sgfopts.analyzeTurns = [0, 1, 2, 3, 4];

    // Be careful. Easy to fail with the changes of comments formats.
    compare(
      'test/examples/t-sabaki-2.json',
      'test/examples/t-sabaki-2-analyzed.sgf',
    );
  });
});
